### ISSUE TITLE
Report website with ads in the app

### ISSUE THREAD

**Issue by raiym** [adhell/android#23]

**Comment by reikar** [comment]
MX Player has adds.

**Comment by k1ng440** [comment]
[Stack](https://play.google.com/store/apps/details?id=com.ketchapp.stack&hl=en) has ads.

**Comment by k1ng440** [comment]
@raiym i am willing to lend a hand if you need.

**Comment by raiym** [comment]
@k1ng440 @reikar hello
thank you.
from 1.5.1 you can ad your own urls packages (hosts files)
only for nougat
