### ISSUE TITLE
com.google.android.music:main" was overloading while GPMusic was Whitelisted.

### ISSUE THREAD

**Issue by tehdef** [adhell/android#24]
Hey guys,

Been plugging in my Galaxy S8+ at night and when I wake up I get this message. 

com.google.android.music:main" was overloading

I close the app, and then move on with my day. It only happens after it's been plugged in for the night. I've already whitelisted Google Play Music, but this branch name isn't something I can find in the Whitelist, so I'm not able to do so. 

Is there anything that Ad Hell can do to help with this? 

Thank you,

**Comment by raiym** [comment]
@tehdef hello, no never saw such thing

**Comment by tehdef** [comment]
@raiym It feels like an extension of the prior whitelisting problem.

**Comment by raiym** [comment]
@tehdef apparently I have fixed it in last release (I whitelist google play music by default)
so you need to turn off and on again and it will fix the problem
