### ISSUE TITLE
Building adhell apk with Android Studio

### ISSUE THREAD

**Issue by fusionjack** [adhell/android#30]
Hi,

Could you please explain how to build adhell apk with Android Studio?
I think the build.gradle needs the fabric properties and these ADHELL_TOKEN, ADHELL_KEY_URL and ADHELL_HEARTBEAT_URL.

Thanks.

Regards,
Chandra

**Comment by raiym** [comment]
@fusionjack I think we have talked though email. 

In short you just should revome code related to this urls and paste your own seap knox key.
