### ISSUE TITLE
Translate into Italian

### ISSUE THREAD

**Issue by ca0ss** [adhell/android#31]
Hello there, for help into traslation i can help you!

**Comment by raiym** [comment]
@ca0ss it would be cool. 
English strings file: https://github.com/adhell/android/blob/master/app/src/main/res/values/strings.xml
And I just have added Italian strings file: https://github.com/adhell/android/blob/master/app/src/main/res/values-it/strings.xml

**Comment by ca0ss** [comment]
@raiym tomorrow will start 😎

**Comment by raiym** [comment]
@ca0ss thank you
