### ISSUE TITLE
UI bug opening recent app and press back

### ISSUE THREAD

**Issue by ca0ss** [adhell/android#38]
https://youtu.be/fJMBa6GVy6w
here a video of the bug:
open app sometimes and close it using home button
when you open it back using recent app menu and press back, the settings icon will be duplicated

**Comment by raiym** [comment]
@ca0ss true

**Comment by ca0ss** [comment]
sometimes the bug became more "heavy"
you can see disable and report button under the settings buttons
Sometimes appear to me, but cannot explain how can replicate the bug
