### ISSUE TITLE
1.5.4 changes ad blocking in apps 

### ISSUE THREAD

**Issue by mk89pwnz** [adhell/android#39]
Before latest update all ads where merging with app design now it's white or shows the icon of not loaded pic, before the update it was clean. Few sc from apps below 

http://imgur.com/OmFcCEf
http://imgur.com/nWca8rA

Any way to fix this? Thanks,BTW best ad blocking and more app!

**Comment by Bec-de-Xorbin** [comment]
After getting frustrated by this, I blacklisted two newly default whitelisted apps (Play Store and Play Services). It's blocking now normally. Whitelist works a bit wonky though, it still shows that those two apps are still whitelisted.

**Comment by mk89pwnz** [comment]
@Bec-de-Xorbin that totally worked, thanks!

**Comment by crkellen** [comment]
With this latest update, I started having ads in Relay for Reddit. I never had them before.
The whitelist is very confusing, if the slider is ON, does that mean the app is whitelisted or blocking ads?

It seems to be that if it is on, it is blocking ads, which is the opposite of the package disabler. If I want to BLOCK ads, should I be turning the slider ON?

**Comment by raiym** [comment]
In v1.5.5 I have disabled whitelist by default. 
So, turn on adhell. and don't whitelist google play services.

I now understand that google play services providers ads in apps.

**Comment by crkellen** [comment]
How do you un-whitelist Google play services?
null

**Comment by raiym** [comment]
Adhell -> Settings -> Whitelist apps -> Turn on Google play services

**Comment by crkellen** [comment]
Why is it that turning ON the app in the whitelist, turns OFF the whitelist for that app? Very confusing as the package disabler is the opposite.
null

**Comment by raiym** [comment]
Yes. 
Will be fixed in next updates. 
Something like this: 
Turn off or turn on adblock for apps

You could propose your way. How it should be?

**Comment by crkellen** [comment]
Yes I agree that using the verbage "Turn on or off Adblock for apps" should be used.
If the slider for the app is ON, so highlighted/flipped to the right, then ads will be BLOCKED in that app, which is the equivalent of turning the whitelist OFF.
null

**Comment by raiym** [comment]
OK thanks @crkellen
