### ISSUE TITLE
Premium subscription problem

### ISSUE THREAD

**Issue by ca0ss** [adhell/android#44]
today I try to open subscription on app to check translation ecc.. but play service say that is 1,59 per day: not for month (according to adhell)
http://imgur.com/a/L3QUp
**play service say that is a free test, but still per day

**Comment by raiym** [comment]
Yes it is per day for you and free for you only @ca0ss

**Comment by raiym** [comment]
and other alpha testers

**Comment by ca0ss** [comment]
thx raiym... check pull request: translated again
