### ISSUE TITLE
Websites won't load after adding another host provider

### ISSUE THREAD

**Issue by neFAST** [adhell/android#47]
Hi, good job with adhell. I tried today to add a custom host file: https://easylist-downloads.adblockplus.org/liste_fr.txt

Now when I try to access a forum like http://forum.hardware.fr the website is blocked. Is this an issue with the list (I use the same one one my desktop PC without issues) or with adhell?

**Comment by raiym** [comment]
@neFAST yes. Because link you have provided is not host file. 
host file looks like this: 
http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext

**Comment by raiym** [comment]
And link you provided have hardware.fr url, so because of it the site is blocked in adhell.

**Comment by neFAST** [comment]
@raiym thanks for the clarification. Do you know a source for "local" host files?
