### ISSUE TITLE
Send information about smartphone software versions (Android, Knox SDKs) if Adhell failed to turn on

### ISSUE THREAD

**Issue by raiym** [adhell/android#7]

**Comment by pseudo-anomalous** [comment]
Thank you for adhell. Your app correctly took me though the process of adding admin and enabling a Knox license on my Samsung Galaxy Pro 12.2. However when I press Turn On the message "Please wait... Enabling Adhell" changes back to "Adhell disabled."

Samsung recently updated the tablet but the Android version remains at 5.0.2. Screenshot of all version numbers attached. Thank you.
![tmp_11929--1540394479](https://cloud.githubusercontent.com/assets/27909470/25310859/f1394eaa-2843-11e7-9327-b152727b1b91.jpeg)

**Comment by raiym** [comment]
@pseudo-anomalous hello
Thank you for the issue. 
Yes, Adhell works fine starting Marshmallow. 
Sadly there is no way to make it work correctly on older versions
